#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Tue Mar 25 21:04:56 2014
#

import wx
from SpiderGUI import *

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

currentName = ''

class NameDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NameDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("\n   Enter your name:       \n"))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("OK"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.GetName, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NameDialog.__set_properties
        self.SetTitle(_("New Highscore!"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NameDialog.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.label_1, 0, 0, 0)
        sizer_7.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        self.Layout()
        # end wxGlade

    def GetName(self, event):  # wxGlade: NameDialog.<event_handler>
        currentName = self.text_ctrl_1.GetValue()
        StoreScore(currentName)
        self.Destroy()

# end of class NameDialog
class HSDialog(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        dialog = NameDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(dialog)
        dialog.Show()
        return 1

# end of class HSDialog

if __name__ == "__main__":
    gettext.install("highscore") # replace with the appropriate catalog name

    highscore = HSDialog(0)
    highscore.MainLoop()